### ISSUE TITLE
Failed Assertion: Debug.Assert(boundary <= right);

### ISSUE THREAD

**Issue by manofstick** [damageboy/VxSort#8]
129 elements all the same...

    VectorizedSort.UnstableSort(new int[129]);

Causes a failed assertion in [`Partition1VectorInPlace`](https://github.com/damageboy/VxSort/blob/9db7cc60b18545df8a1b5ca8b8a5e5a1a1bc7534/VxSort/VectorizedSort.cs#L838):

    Debug.Assert(boundary <= right);

Or if you do 

    VectorizedSort.UnstableSort(new int[152]);

There you get the equivalent exception in [`Partition8VectorsInPlace`](https://github.com/damageboy/VxSort/blob/9db7cc60b18545df8a1b5ca8b8a5e5a1a1bc7534/VxSort/VectorizedSort.cs#L541).

**Comment by damageboy** [comment]
Thanks for the report, I have something similar in my tests, but I think I know what specific (and untested) path this is triggering...

There is a size range just between 112..152, IIRC,
Where this code paths triggered and failing...

Will keep you posted :)

**Comment by damageboy** [comment]
Hmm...
I've not managed to reproduce this cleanly in my research branch with [this commit](https://github.com/damageboy/VxSort/commit/a67c00e160d550e644fcd4a258909a44e126a5da)

I'll start digging deeper, but I have a feeling this might also be related to alignment issues (that's the only case I've ever had for flaky-tests).

On it... :)

Again, thanks for reporting!
